name: Build Praxiom Health Firmware
on:
  push:
    branches: [ main, health-build ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: infinitime/infinitime-build
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Build firmware
      run: |
        cmake -B build -DBUILD_DFU=1 -DBUILD_RESOURCES=1
        cmake --build build -j4
    
    - name: Upload DFU artifact
      uses: actions/upload-artifact@v3
      with:
        name: pinetime-dfu
        path: build/src/pinetime-mcuboot-app-dfu-*.zip
